f<-function(x,y){(x+y)/30}
f1<-function(x,y){x*y*f(x,y)}
x<-c(0,1,2,3)
y<-c(0:2)
M=matrix(c(f(0,c(0:2)),f(1,c(0:2)),f(2,c(0:2)),f(3,c(0:2))),nrow=4,ncol=3,byrow=TRUE)
M1=matrix(c(f1(0,c(0:2)),f1(1,c(0:2)),f1(2,c(0:2)),f1(3,c(0:2))),nrow=4,ncol=3,byrow=TRUE)
gx=apply(M,1,sum) 
hx=apply(M,2,sum) 
EX=sum(x*gx)
print(EX)
EX2=sum(x^2*gx)
print(EX2)
Varx=EX2-(EX)^2
print(Varx)
EY=(sum(y*hx))
EY2=(sum(y^2*hx))
Vary=EY2-(EY)^2
print(EY)
#covariance=Exy-Ex*Ey
Exy=sum(M1)
print(Exy)
covx=Exy-EX*EY
print(covx)
correla=covx/sqrt(Varx*Vary)
print(correla)